version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ecochain
      POSTGRES_PASSWORD: ecochain
      POSTGRES_DB: ecochain
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - eco-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://f0b7296a7fbd5dfc8e4c31e0266104bf5094d4b31c6dafadce1e54290fdacc8f:sk_9e571QmXbdktonKT3ffdc@pooled.db.prisma.io:5432/postgres?sslmode=require
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_ZnVuLWNpdmV0LTUzLmNsZXJrLmFjY291bnRzLmRldiQ
      CLERK_SECRET_KEY: sk_test_ENB7SCWGVHTdmnIQGi0QYwlQfoxQgun8TAzrpWh6fJ
      NEXT_PUBLIC_INITIA_CHAIN_ID: ecochain105
      NEXT_PUBLIC_INITIA_ROUTER_API_URL: https://router.initia.xyz
      NEXT_PUBLIC_INITIA_REGISTRY_URL: https://registry.initia.xyz
      NEXT_PUBLIC_INITIA_GLYPH_URL: https://glyph.initia.xyz
    networks:
      - eco-network

  rapid-relayer:
    image: ghcr.io/initia-labs/rapid-relayer:v1.0.8
    working_dir: /usr/rapid-relayer
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ./relayer-config.json:/usr/rapid-relayer/config.json:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
      - METRIC_PORT=3002
      - LOG_LEVEL=info
      - CONFIGFILE=/usr/rapid-relayer/config.json
      - RELAYER_KEY_ECOCHAIN105=test
      - RELAYER_KEY_INITIATION2=test
    networks:
      - eco-network
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  db-data:

networks:
  eco-network:
